platform: linux

image_resource:
  type: registry-image
  source:
    repository: bosh/integration

inputs:
- name: bosh-cpi-src

outputs:
- name: releases

run:
  path: bosh-cpi-src/ci/tasks/build.sh
