platform: linux

image_resource:
  type: registry-image
  source:
    repository: bosh/integration

inputs:
- name: bosh-cpi-src
- name: pipeline-bosh-warden-cpi-tarball
- name: dev-version

outputs:
- name: bosh-cpi-src

run:
  path: bosh-cpi-src/ci/tasks/promote.sh

params:
  PRIVATE_YML:
