---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: boshcpi/gce-cpi-release
inputs:
  - name: bosh-cpi-src
  - name: bosh-cli
  - name: bosh-cpi-release
  - name: bosh-deployment
  - name: stemcell
outputs:
  - name: deployment
run:
  path: bosh-cpi-src/ci/tasks/setup-deployment.sh
