---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: foundationalinfrastructure/gce-cpi-release
inputs:
  - name: bosh-warden-cpi-release
  - name: bosh-cli
  - name: bosh-cpi-release
  - name: bosh-deployment
  - name: jumpbox-deployment
  - name: deployment
  - name: infrastructure
  - name: stemcell
outputs:
  - name: director-creds
  - name: director-state
  - name: jumpbox-creds
  - name: jumpbox-state

run:
  path: bosh-warden-cpi-release/ci/tasks/setup-director.sh
  user: non-root-user
params:
  BOSH_INIT_LOG_LEVEL:            warn
  google_subnetwork_range:        replace-me
  google_json_key_data:           replace-me
  google_test_bucket_name:        replace-me
