---
jobs:
- name: build
  serial: true
  plan:
  - in_parallel:
    - get: bosh-ecosystem-docker-image
    - {get: bosh-warden-cpi-release, trigger: true}
    - {get: dev-version, params: {bump: patch}}
  - put: dev-version
    params: {file: dev-version/number}
  - task: build
    image: bosh-ecosystem-docker-image
    config:
      platform: linux
      inputs:
      - name: bosh-warden-cpi-release
      - name: dev-version
      outputs:
      - name: releases
      run: {path: bosh-warden-cpi-release/ci/build-release.sh}
      params:
        BOSH_ENVIRONMENT: ((iaas_directors_gcp-director_bosh_environment))
        BOSH_CA_CERT: ((iaas_directors_gcp-director_bosh_ca_cert.ca))
        BOSH_CLIENT: ((iaas_directors_gcp-director_bosh_client.username))
        BOSH_CLIENT_SECRET: ((iaas_directors_gcp-director_bosh_client.password))
        JUMPBOX_PRIVATE_KEY: ((iaas_directors_gcp-director_bosh_jumpbox_ssh.private_key))
        JUMPBOX_USERNAME: ((iaas_directors_gcp-director_bosh_jumpbox_username))
        JUMPBOX_IP: ((iaas_directors_gcp-director_bosh_jumpbox_ip))
  - put: pipeline-bosh-warden-cpi-tarball
    params: {file: releases/bosh-warden-cpi-*.tgz}

- name: bats
  serial: true
  plan:
  - in_parallel:
    - {get: bosh-ecosystem-concourse}
    - {get: bosh-ecosystem-docker-image}
    - {get: bosh-warden-cpi-release}
    - {get: bosh-acceptance-tests}
    - {get: pipeline-bosh-warden-cpi-tarball, passed: [build], trigger: true}
    - {get: warden-ubuntu-jammy-stemcell, params: {tarball: false}}
    - {get: iaas-stemcell, resource: google-ubuntu-jammy-stemcell, params: {tarball: false}}
    - {get: dev-version, passed: [build]}
    - get: bosh-release
    - get: garden-linux-release
  - task: clean-credhub
    file: bosh-ecosystem-concourse/tasks/shared/delete-credhub-entries.yml
    image: bosh-ecosystem-docker-image
    params:
      CREDHUB_CA_CERT_STRING: ((iaas_directors_gcp-director_bosh_credhub_ca_cert.ca))
      CREDHUB_CLIENT: ((iaas_directors_gcp-director_bosh_credhub_client.username))
      CREDHUB_SECRET: ((iaas_directors_gcp-director_bosh_credhub_client.password))
      CREDHUB_SERVER: ((iaas_directors_gcp-director_bosh_credhub_server))
      JUMPBOX_PRIVATE_KEY: ((iaas_directors_gcp-director_bosh_jumpbox_ssh.private_key))
      JUMPBOX_URL: "((iaas_directors_gcp-director_bosh_jumpbox_ip)):22"
      PATH_TO_DELETE: "/concourse/bosh-warden-cpi-bats-director/"
  - task: bats
    file: bosh-warden-cpi-release/ci/tasks/bats.yml
    image: bosh-ecosystem-docker-image
    params:
      BOSH_ENVIRONMENT: ((iaas_directors_gcp-director_bosh_environment))
      BOSH_CA_CERT: ((iaas_directors_gcp-director_bosh_ca_cert.ca))
      BOSH_CLIENT: ((iaas_directors_gcp-director_bosh_client.username))
      BOSH_CLIENT_SECRET: ((iaas_directors_gcp-director_bosh_client.password))
      JUMPBOX_PRIVATE_KEY: ((iaas_directors_gcp-director_bosh_jumpbox_ssh.private_key))
      JUMPBOX_USERNAME: ((iaas_directors_gcp-director_bosh_jumpbox_username))
      JUMPBOX_IP: ((iaas_directors_gcp-director_bosh_jumpbox_ip))
      CREDHUB_CLIENT: ((iaas_directors_gcp-director_bosh_credhub_client.username))
      CREDHUB_SECRET: ((iaas_directors_gcp-director_bosh_credhub_client.password))
      CREDHUB_CA_PEM: ((iaas_directors_gcp-director_bosh_credhub_ca_cert.ca))

- name: promote
  serial: true
  plan:
  - in_parallel:
    - get: dev-version
      passed: [bats]
      params:
        bump: major
    - {get: bosh-ecosystem-docker-image}
    - {get: bosh-warden-cpi-release}
    - {get: pipeline-bosh-warden-cpi-tarball, passed: [bats]}
  - task: promote
    file: bosh-warden-cpi-release/ci/tasks/promote.yml
    image: bosh-ecosystem-docker-image
    params:
      BOSH_AWS_ACCESS_KEY_ID: ((warden_assume_aws_access_key.username))
      BOSH_AWS_SECRET_ACCESS_KEY: ((warden_assume_aws_access_key.password))
      BOSH_AWS_ROLE_ARN: ((warden_assume_aws_access_key.role_arn))
  - put: dev-version
    params: { file: dev-version/number }
  - put: bosh-warden-cpi-release
    resource: promoted-bosh-warden-cpi-release
    params:
      repository: bosh-warden-cpi-release
      rebase: true
      tag_prefix: v
      tag: bosh-warden-cpi-release/final_version

resource_types:
- name: semver
  type: docker-image
  source:
    repository: concourse/semver-resource
    tag: 1.6

resources:
- name: dev-version
  type: semver
  source:
    key: dev-version
    bucket: bosh-warden-cpi-tarball
    access_key_id: ((bosh_cpis_assume_aws_access_key.username))
    secret_access_key: ((bosh_cpis_assume_aws_access_key.password))
    assume_role_arn: ((bosh_cpis_assume_aws_access_key.role_arn))
    initial_version: 42.0.0

- name: pipeline-bosh-warden-cpi-tarball
  type: s3
  source:
    bucket: bosh-warden-cpi-tarball
    regexp: bosh-warden-cpi-(.*).tgz
    access_key_id: ((bosh_cpis_assume_aws_access_key.username))
    secret_access_key: ((bosh_cpis_assume_aws_access_key.password))
    aws_role_arn: ((bosh_cpis_assume_aws_access_key.role_arn))

- name: bosh-acceptance-tests
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh-acceptance-tests
    branch: master

- name: bosh-ecosystem-concourse
  type: git
  source:
    uri: git@github.com:pivotal/bosh-ecosystem-concourse.git
    private_key: ((github_deploy_key_bosh_ecosystem_concourse.private_key))

- name: bosh-warden-cpi-release
  type: git
  source:
    uri: git@github.com:cloudfoundry/bosh-warden-cpi-release.git
    branch: master
    private_key: ((github_deploy_key_bosh-warden-cpi-release.private_key))
    ignore_paths:
    - releases/**/*.yml

- name: promoted-bosh-warden-cpi-release
  type: git
  source:
    uri: git@github.com:cloudfoundry/bosh-warden-cpi-release.git
    branch: master
    private_key: ((github_deploy_key_bosh-warden-cpi-release.private_key))

- name: warden-ubuntu-jammy-stemcell
  type: bosh-io-stemcell
  source: {name: bosh-warden-boshlite-ubuntu-jammy-go_agent}

- name: google-ubuntu-jammy-stemcell
  type: bosh-io-stemcell
  source: {name: bosh-google-kvm-ubuntu-jammy-go_agent}

- name: bosh-release
  type: bosh-io-release
  source: {repository: cloudfoundry/bosh}

- name: garden-linux-release
  type: bosh-io-release
  source: {repository: cloudfoundry-incubator/garden-linux-release}

- name: bosh-ecosystem-docker-image
  type: registry-image
  source:
    repository: bosh/bosh-ecosystem-concourse
    username: ((docker.username))
    password: ((docker.password))
