---
jobs:
- name: build
  serial: true
  plan:
  - in_parallel:
    - get: bosh-ecosystem-docker-image
    - {get: bosh-warden-cpi-release, trigger: true}
    - {get: dev-version, params: {bump: patch}}
  - put: dev-version
    params: {file: dev-version/number}
  - task: build
    image: bosh-ecosystem-docker-image
    config:
      platform: linux
      inputs:
      - name: bosh-warden-cpi-release
      - name: dev-version
      outputs:
      - name: releases
      run: {path: bosh-warden-cpi-release/ci/build-release.sh}
      params:
        BOSH_ENVIRONMENT: ((iaas_directors_gcp-director_bosh_environment))
        BOSH_CA_CERT: ((iaas_directors_gcp-director_bosh_ca_cert.ca))
        BOSH_CLIENT: ((iaas_directors_gcp-director_bosh_client.username))
        BOSH_CLIENT_SECRET: ((iaas_directors_gcp-director_bosh_client.password))
        JUMPBOX_PRIVATE_KEY: ((iaas_directors_gcp-director_bosh_jumpbox_ssh.private_key))
        JUMPBOX_USERNAME: ((iaas_directors_gcp-director_bosh_jumpbox_username))
        JUMPBOX_IP: ((iaas_directors_gcp-director_bosh_jumpbox_ip))
  - put: pipeline-bosh-warden-cpi-tarball
    params: {file: releases/bosh-warden-cpi-*.tgz}

- name: bats
  serial: true
  plan:
  - in_parallel:
    - {get: bosh-ecosystem-docker-image}
    - {get: bosh-warden-cpi-release}
    - {get: bosh-acceptance-tests}
    - {get: pipeline-bosh-warden-cpi-tarball, passed: [build], trigger: true}
    - {get: warden-ubuntu-bionic-stemcell, params: {tarball: false}}
    - {get: google-ubuntu-bionic-stemcell, params: {tarball: false}}
    - {get: dev-version, passed: [build]}
    - get: bosh-release
    - get: garden-linux-release
  - task: bats
    file: bosh-warden-cpi-release/ci/tasks/bats.yml
    image: bosh-ecosystem-docker-image
    params:
      BOSH_ENVIRONMENT: ((iaas_directors_gcp-director_bosh_environment))
      BOSH_CA_CERT: ((iaas_directors_gcp-director_bosh_ca_cert.ca))
      BOSH_CLIENT: ((iaas_directors_gcp-director_bosh_client.username))
      BOSH_CLIENT_SECRET: ((iaas_directors_gcp-director_bosh_client.password))
      JUMPBOX_PRIVATE_KEY: ((iaas_directors_gcp-director_bosh_jumpbox_ssh.private_key))
      JUMPBOX_USERNAME: ((iaas_directors_gcp-director_bosh_jumpbox_username))
      JUMPBOX_IP: ((iaas_directors_gcp-director_bosh_jumpbox_ip))
      CREDHUB_CLIENT: ((iaas_directors_gcp-director_bosh_credhub_client.username))
      CREDHUB_SECRET: ((iaas_directors_gcp-director_bosh_credhub_client.password))
      CREDHUB_CA_PEM: ((iaas_directors_gcp-director_bosh_credhub_ca_cert.ca))
      RECREATE: true
      SKIP_BUNDLE_INSTALL: true

- name: promote
  serial: true
  plan:
  - in_parallel:
    - get: dev-version
      passed: [bats]
      params:
        bump: major
    - {get: bosh-ecosystem-docker-image}
    - {get: bosh-warden-cpi-release}
    - {get: pipeline-bosh-warden-cpi-tarball, passed: [bats]}
  - task: promote
    file: bosh-warden-cpi-release/ci/tasks/promote.yml
    image: bosh-ecosystem-docker-image
    params:
      BOSH_AWS_ACCESS_KEY_ID: ((final_blobs_iam_credentials.username))
      BOSH_AWS_SECRET_ACCESS_KEY: ((final_blobs_iam_credentials.password))
      
  - put: bosh-warden-cpi-release
    resource: promoted-bosh-warden-cpi-release
    params:
      repository: bosh-warden-cpi-release
      rebase: true
      tag_prefix: v
      tag: bosh-warden-cpi-release/final_version

resources:
- name: dev-version
  type: semver
  source:
    key: dev-version
    bucket: ((s3_pipeline_bucket))
    access_key_id: ((s3_pipeline_access_key_id))
    secret_access_key: ((s3_pipeline_secret_access_key))
    initial_version: 42.0.0

- name: pipeline-bosh-warden-cpi-tarball
  type: s3
  source:
    bucket: ((s3_pipeline_bucket))
    regexp: bosh-warden-cpi-(.*).tgz
    access_key_id: ((s3_pipeline_access_key_id))
    secret_access_key: ((s3_pipeline_secret_access_key))

- name: bosh-acceptance-tests
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh-acceptance-tests
    branch: master

- name: bosh-warden-cpi-release
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh-warden-cpi-release.git
    branch: master
    ignore_paths:
    - releases/**/*.yml

- name: promoted-bosh-warden-cpi-release
  type: git
  source:
    uri: git@github.com:cloudfoundry/bosh-warden-cpi-release.git
    branch: master
    private_key: ((github_promote_private_key))

- name: warden-ubuntu-bionic-stemcell
  type: bosh-io-stemcell
  source: {name: bosh-warden-boshlite-ubuntu-bionic-go_agent}

- name: google-ubuntu-bionic-stemcell
  type: bosh-io-stemcell
  source: {name: bosh-google-kvm-ubuntu-bionic-go_agent}

- name: bosh-release
  type: bosh-io-release
  source: {repository: cloudfoundry/bosh}

- name: garden-linux-release
  type: bosh-io-release
  source: {repository: cloudfoundry-incubator/garden-linux-release}

- name: bosh-ecosystem-docker-image
  type: registry-image
  source:
    repository: bosh/bosh-ecosystem-concourse
    username: ((docker.username))
    password: ((docker.password))
