---
jobs:
- name: build
  serial: true
  plan:
  - in_parallel:
    - get: bosh-warden-cpi-release
    - {get: dev-version, params: {bump: patch}}
  - put: dev-version
    params: {file: dev-version/number}
  - task: build
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: { repository: bosh/bosh-ecosystem-concourse }
      inputs:
      - name: bosh-warden-cpi-release
      - name: dev-version
      run: {path: bosh-warden-cpi-release/ci/build-release.sh}
      params:
        BOSH_ENVIRONMENT: ((iaas_directors_gcp-director_bosh_environment))
        BOSH_CA_CERT: ((iaas_directors_gcp-director_bosh_ca_cert.ca))
        BOSH_CLIENT: ((iaas_directors_gcp-director_bosh_client.username))
        BOSH_CLIENT_SECRET: ((iaas_directors_gcp-director_bosh_client.password))
        JUMPBOX_PRIVATE_KEY: ((iaas_directors_gcp-director_bosh_jumpbox_ssh.private_key))
        JUMPBOX_USERNAME: ((iaas_directors_gcp-director_bosh_jumpbox_username))
        JUMPBOX_IP: ((iaas_directors_gcp-director_bosh_jumpbox_ip))
  - put: pipeline-bosh-warden-cpi-tarball
    params: {from: build/out/bosh-warden-cpi-.*\.tgz}

- name: bats
  serial: true
  plan:
  - in_parallel:
    - {get: bosh-warden-cpi-release, passed: [build]}
    - {get: pipeline-bosh-warden-cpi-tarball, passed: [build], trigger: true}
    - {get: warden-ubuntu-bionic-stemcell, params: {tarball: false}}
    - get: bosh-release
    - get: garden-linux-release
  - task: bats
    config:
      image_resource:
        type: registry-image
        source: { repository: bosh/bosh-ecosystem-concourse }
      platform: linux
      inputs:
      - name: bosh-warden-cpi-release
      - name: pipeline-bosh-warden-cpi-tarball
      - name: warden-ubuntu-bionic-stemcell
      - name: bosh-release
      - name: garden-linux-release
      run: {path: bosh-warden-cpi-release/ci/bats.sh}
      params:
        BOSH_ENVIRONMENT: ((iaas_directors_gcp-director_bosh_environment))
        BOSH_CA_CERT: ((iaas_directors_gcp-director_bosh_ca_cert.ca))
        BOSH_CLIENT: ((iaas_directors_gcp-director_bosh_client.username))
        BOSH_CLIENT_SECRET: ((iaas_directors_gcp-director_bosh_client.password))
        JUMPBOX_PRIVATE_KEY: ((iaas_directors_gcp-director_bosh_jumpbox_ssh.private_key))
        JUMPBOX_USERNAME: ((iaas_directors_gcp-director_bosh_jumpbox_username))
        JUMPBOX_IP: ((iaas_directors_gcp-director_bosh_jumpbox_ip))
- name: promote
  serial: true
  plan:
  - in_parallel:
    - {get: bosh-warden-cpi-release, passed: [bats]}
    - {get: pipeline-bosh-warden-cpi-tarball, passed: [bats], trigger: true}
  - task: promote
    file:
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: { repository: bosh/bosh-ecosystem-concourse }
      inputs:
      - name: bosh-warden-cpi-release
      - name: pipeline-bosh-warden-cpi-tarball
      run: {path: bosh-warden-cpi-release/ci/promote-release.sh}
      params:
        BOSH_AWS_ACCESS_KEY_ID: {{promote_access_key_id}}
        BOSH_AWS_SECRET_ACCESS_KEY: {{promote_secret_access_key}}
  - put: bosh-warden-cpi-release
    resource: promoted-bosh-warden-cpi-release
    params:
      repository: promote/bosh-warden-cpi-release
      rebase: true
      tag_prefix: v
      tag: promote/final_version

resources:
- name: dev-version
  type: semver
  source:
    key: dev-version
    bucket: {{s3_pipeline_bucket}}
    access_key_id: {{s3_pipeline_access_key_id}}
    secret_access_key: {{s3_pipeline_secret_access_key}}
    initial_version: 42.0.0

- name: pipeline-bosh-warden-cpi-tarball
  type: s3
  source:
    bucket: {{s3_pipeline_bucket}}
    regexp: bosh-warden-cpi-(.*).tgz
    access_key_id: {{s3_pipeline_access_key_id}}
    secret_access_key: {{s3_pipeline_secret_access_key}}

- name: bosh-warden-cpi-release
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh-warden-cpi-release
    branch: update_ci
    ignore_paths:
    - releases/**/*.yml

- name: promoted-bosh-warden-cpi-release
  type: git
  source:
    uri: git@github.com:cloudfoundry/bosh-warden-cpi-release.git
    branch: update_ci
    private_key: {{github_promote_private_key}}

- name: warden-ubuntu-bionic-stemcell
  type: bosh-io-stemcell
  source: {name: bosh-warden-boshlite-ubuntu-bionic-go_agent}

- name: bosh-release
  type: bosh-io-release
  source: {repository: cloudfoundry/bosh}

- name: garden-linux-release
  type: bosh-io-release
  source: {repository: cloudfoundry-incubator/garden-linux-release}
